# Generated by Django 5.1.1 on 2024-10-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvocadoAvenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn', models.CharField(max_length=100, unique=True)),
                ('type_of_fruit', models.CharField(max_length=256)),
                ('initial_weight', models.IntegerField()),
                ('fruid_cost', models.FloatField()),
                ('sorted_weight', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
