# Generated by Django 5.1.1 on 2024-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocadoavenue',
            name='grn',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
